export const SESSIONID_CHANGE = "SESSIONID_CHANGE";
export const CURRENT_VOTER_CHANGE = "CURRENT_VOTER_CHANGE";
export const MY_USER_CHANGE = "MY_USER_CHANGE";
export const QUEUE_LENGHT_CHANGE = "QUEUE_LENGHT_CHANGE";
